add comments and move scripts to new .jekyll-build-scripts folder at root

diff --git a/.github/workflows/build-website.yaml b/.github/workflows/build-website.yaml
--- a/.github/workflows/build-website.yaml
+++ b/.github/workflows/build-website.yaml
@@ -77,27 +77,30 @@ jobs:
           echo 'WF_CURRENT_DATE_TIME value: $WF_CURRENT_DATE_TIME'
           echo 'Make it okay to run git commands in the source folder'
           git config --global --add safe.directory ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}
+          echo 'Go to the root folder where Git files exist'
           cd ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}
           echo 'Run Python script to display current date and time'
-          python3 print-date-time.py
+          python3 .jekyll-build-scripts/print-date-time/print-date-time.py
           echo 'Here is a list of the files in ${{ env.WORKSPACE_PATH }}${{ env.REPO_NAME }}'
           ls -la
           echo 'bundle install'
           bundle install
           echo 'bundle update'
           bundle update
+          echo 'Build the Jekyll site'
           bundle exec jekyll build --future
           "
 
-      - name: Cleanup Temporary Docker Resources
-        run: |
-          docker stop ${{ env.BUILD_TEMP_CONTAINER }} || true
-          docker rm ${{ env.BUILD_TEMP_CONTAINER }} || true
-          docker rmi ${{ env.BUILD_TEMP_IMAGE }} || true
-
-      - name: Print workflow completion
-        run: |
+          - name: Print workflow completion
+          run: |
           echo "Workflow complete"
+          
+# #* Utility: Use this code to cleanup temporary files in GitHub
+# - name: Cleanup Temporary Docker Resources
+#   run: |
+#     docker stop ${{ env.BUILD_TEMP_CONTAINER }} || true
+#     docker rm ${{ env.BUILD_TEMP_CONTAINER }} || true
+#     docker rmi ${{ env.BUILD_TEMP_IMAGE }} || true
 
 # #* Utility: Use this code after any step to exit/fail the workflow
 # - name: Exit workflow for testing purposes
